name: 'transaction_tracing'
version: '1.0.0'
config-version: 2

profile: 'default'  # Adjust to your Snowflake profile in config/profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transaction_tracing:
    +materialized: view
    staged:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: analytics
      +materialized: table