name: 'bitcoin_transaction_tracing'
version: '1.0.0'
config-version: 2

profile: 'default'  # Adjust to your Snowflake profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  bitcoin_transaction_tracing:
    +database: BLOCKCHAIR  # Replace with your Snowflake database name
    staged:
      +materialized: view
      +schema: staged

require-dbt-version: ">=1.0.0"