CREATE OR REPLACE TABLE outputs_raw (
    BLOCK_ID INTEGER,
    TRANSACTION_HASH VARCHAR(64),
    INDEX INTEGER,
    TIME VARCHAR(32),
    VALUE INTEGER,
    VALUE_USD FLOAT,
    RECIPIENT VARCHAR(64),
    TYPE VARCHAR(32),
    SCRIPT_HEX VARCHAR(256),
    IS_FROM_COINBASE INTEGER,
    IS_SPENDABLE INTEGER
);